In [1]:
import torch

In [28]:
from torch import linalg as LA

x = torch.rand((10,256))
y = torch.rand((10,256))
M= x.unsqueeze(1).permute(0,2,1)*y.unsqueeze(1)

LA.matrix_norm(M, ord='fro')

tensor([82.5135, 89.7705, 80.8988, 87.9380, 83.6055, 86.0845, 82.2016, 90.9168,
        83.2159, 88.0587])

In [27]:
x = torch.rand((10,3))
y = torch.rand((10,3))
M= x.unsqueeze(1).permute(0,2,1)*y.unsqueeze(1)
oth = LA.cross(x,y)
M1= oth.unsqueeze(1).permute(0,2,1)*y.unsqueeze(1)
M2= oth.unsqueeze(1).permute(0,2,1)*x.unsqueeze(1)
LA.matrix_norm(M, ord='fro'),LA.matrix_norm(M1, ord='fro'),LA.matrix_norm(M2, ord='fro')

(tensor([1.4087, 1.9057, 1.1123, 1.4260, 1.2148, 0.5948, 1.0255, 0.7873, 1.8428,
         1.0439]),
 tensor([1.0975, 0.4052, 0.7743, 0.5284, 0.6926, 0.1593, 0.6101, 0.2385, 1.1444,
         0.1200]),
 tensor([1.1074, 0.5435, 1.0699, 0.4544, 0.5976, 0.5531, 0.8890, 0.3829, 0.9536,
         0.2187]))

In [16]:
LA.cross(x,y).shape, x.shape

(torch.Size([10, 3]), torch.Size([10, 3]))

In [17]:
LA.cross(x,y)

tensor([[ 3.5670e-01, -2.5734e-01, -3.5764e-01],
        [-4.2816e-01,  3.2093e-01,  8.2876e-02],
        [-2.2654e-01,  7.0428e-01, -2.1356e-01],
        [ 2.5189e-01, -4.9627e-02, -2.4716e-01],
        [ 2.4877e-01, -2.8932e-02, -3.0688e-04],
        [ 6.4856e-01,  2.6693e-01, -4.8360e-01],
        [-3.3991e-01,  3.7135e-01, -1.8108e-01],
        [ 1.5311e-01, -2.2268e-01,  1.0734e-01],
        [-5.5849e-01,  2.9437e-01, -2.6542e-02],
        [-2.4627e-01, -3.7406e-02,  4.4528e-02]])

# Testing with true orthogonal vector 

In [30]:
x = torch.tensor([1.,0,0])
y = torch.tensor([0,1.,0])
z = torch.tensor([0,0,1.])

M1 = x.unsqueeze(0).permute(1,0)*y.unsqueeze(0)
LA.matrix_norm(M1, ord='fro')

tensor(1.)

In [31]:
torch.cross(x,z)

tensor([ 0., -1.,  0.])

In [32]:
M2 = x.unsqueeze(0).permute(1,0)*torch.cross(x,z).unsqueeze(0)
LA.matrix_norm(M2, ord='fro')

tensor(1.)

In [33]:
x.unsqueeze(0).permute(1,0)*torch.cross(x,z).unsqueeze(0)

tensor([[ 0., -1.,  0.],
        [ 0., -0.,  0.],
        [ 0., -0.,  0.]])

In [34]:
x.unsqueeze(0)*torch.cross(x,z).unsqueeze(0).permute(1,0)

tensor([[ 0.,  0.,  0.],
        [-1., -0., -0.],
        [ 0.,  0.,  0.]])

In [21]:
M1

tensor([[0., 1., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [19]:
M1 = x.unsqueeze(0).permute(1,0)*y.unsqueeze(0)
LA.matrix_norm(M1, ord='fro')

tensor(1.)